import types from 'lib/default-ranges/types'

export default {
    name: "Small Blind Raise First In",
    range: [
        {
            "id": "41d28844-3716-4675-87b2-d2ad37fe7a5d",
            "color": "red",
            "name": "Raise/4-Bet",
            "selectedCombos": {
                "22": [],
                "33": [],
                "44": [],
                "55": [],
                "66": [],
                "77": [],
                "88": [],
                "99": [],
                "AKs": [
                    "AcKc",
                    "AdKd",
                    "AhKh",
                    "AsKs"
                ],
                "KK": [
                    "KcKd",
                    "KcKh",
                    "KcKs",
                    "KdKh",
                    "KdKs",
                    "KhKs"
                ],
                "AQo": [
                    "AcQd",
                    "AcQh",
                    "AcQs",
                    "AdQc",
                    "AdQh",
                    "AdQs",
                    "AhQc",
                    "AhQd",
                    "AhQs",
                    "AsQc",
                    "AsQd",
                    "AsQh"
                ],
                "AJo": [
                    "AcJd",
                    "AcJh",
                    "AcJs",
                    "AdJc",
                    "AdJh",
                    "AdJs",
                    "AhJc",
                    "AhJd",
                    "AhJs",
                    "AsJc",
                    "AsJd",
                    "AsJh"
                ],
                "KJo": [
                    "KcJd",
                    "KcJh",
                    "KcJs",
                    "KdJc",
                    "KdJh",
                    "KdJs",
                    "KhJc",
                    "KhJd",
                    "KhJs",
                    "KsJc",
                    "KsJd",
                    "KsJh"
                ],
                "QQ": [
                    "QcQd",
                    "QcQh",
                    "QcQs",
                    "QdQh",
                    "QdQs",
                    "QhQs"
                ],
                "JTs": [],
                "JJ": [
                    "JcJd",
                    "JcJh",
                    "JcJs",
                    "JdJh",
                    "JdJs",
                    "JhJs"
                ],
                "AA": [],
                "AKo": [],
                "AQs": [],
                "AJs": [],
                "KQs": [],
                "ATs": [],
                "A9s": [],
                "A8s": [],
                "A7s": [],
                "A4s": [],
                "A5s": [],
                "A6s": [],
                "A3s": [],
                "A2s": [],
                "KJs": [],
                "KTs": [],
                "K8s": [],
                "QJs": [],
                "QTs": [],
                "K9s": [],
                "Q9s": [],
                "J9s": [],
                "K9o": [],
                "Q9o": [],
                "J9o": [],
                "TT": [],
                "KQo": [],
                "QJo": [],
                "JTo": [],
                "QTo": [],
                "KTo": [],
                "ATo": [],
                "A9o": [],
                "K3s": [],
                "K2s": [],
                "K5s": [],
                "Q5s": [],
                "Q4s": [],
                "Q3s": [],
                "Q2s": [],
                "J7s": [],
                "J6s": [],
                "J5s": [],
                "J4s": [],
                "T6s": [],
                "T5s": [],
                "96s": [],
                "64s": [],
                "53s": [],
                "54s": [],
                "65s": [],
                "K4s": [],
                "K6s": [],
                "Q6s": [],
                "Q7s": [],
                "K7s": [],
                "Q8s": [],
                "J8s": [],
                "T8s": [],
                "98s": [],
                "T7s": [],
                "97s": [],
                "87s": [],
                "86s": [],
                "76s": [],
                "75s": [],
                "85s": [],
                "T9s": [],
                "T9o": [],
                "98o": [],
                "T8o": [],
                "A8o": [],
                "K8o": [],
                "A7o": [],
                "K7o": [],
                "A6o": [],
                "A4o": [],
                "A5o": [],
                "J2s": [],
                "J3s": [],
                "T3s": [],
                "T4s": [],
                "94s": [],
                "84s": [],
                "83s": [],
                "73s": [],
                "62s": [],
                "52s": [],
                "42s": [],
                "32s": [],
                "43s": [],
                "63s": [],
                "74s": [],
                "95s": [],
                "T2s": [],
                "Q8o": [],
                "J8o": [],
                "A3o": [],
                "A2o": [],
                "K4o": [],
                "K5o": [],
                "K6o": [],
                "Q5o": [],
                "Q6o": [],
                "Q7o": [],
                "J7o": [],
                "T7o": [],
                "97o": [],
                "87o": [],
                "86o": [],
                "76o": [],
                "65o": [],
                "54o": []
            }
        },
        {
            "id": "7a2a876c-4d92-4db9-b58a-2aa33f1dd16d",
            "color": "blue",
            "name": "Raise/Call",
            "selectedCombos": {
                "22": [
                    "2c2d",
                    "2c2h",
                    "2c2s",
                    "2d2h",
                    "2d2s",
                    "2h2s"
                ],
                "33": [
                    "3c3d",
                    "3c3h",
                    "3c3s",
                    "3d3h",
                    "3d3s",
                    "3h3s"
                ],
                "44": [],
                "55": [],
                "66": [],
                "77": [],
                "88": [],
                "99": [],
                "AKs": [],
                "KK": [],
                "AQo": [],
                "AJo": [],
                "KJo": [],
                "QQ": [],
                "JTs": [
                    "JcTc",
                    "JdTd",
                    "JhTh",
                    "JsTs"
                ],
                "JJ": [],
                "AA": [],
                "AKo": [],
                "AQs": [],
                "AJs": [],
                "KQs": [],
                "ATs": [
                    "AcTc",
                    "AdTd",
                    "AhTh",
                    "AsTs"
                ],
                "A9s": [
                    "Ac9c",
                    "Ad9d",
                    "Ah9h",
                    "As9s"
                ],
                "A8s": [
                    "Ac8c",
                    "Ad8d",
                    "Ah8h",
                    "As8s"
                ],
                "A7s": [
                    "Ac7c",
                    "Ad7d",
                    "Ah7h",
                    "As7s"
                ],
                "A4s": [],
                "A5s": [
                    "Ac5c",
                    "Ad5d",
                    "Ah5h",
                    "As5s"
                ],
                "A6s": [],
                "A3s": [],
                "A2s": [],
                "KJs": [
                    "KcJc",
                    "KdJd",
                    "KhJh",
                    "KsJs"
                ],
                "KTs": [
                    "KcTc",
                    "KdTd",
                    "KhTh",
                    "KsTs"
                ],
                "K8s": [
                    "Kc8c",
                    "Kd8d",
                    "Kh8h",
                    "Ks8s"
                ],
                "QJs": [
                    "QcJc",
                    "QdJd",
                    "QhJh",
                    "QsJs"
                ],
                "QTs": [
                    "QcTc",
                    "QdTd",
                    "QhTh",
                    "QsTs"
                ],
                "K9s": [],
                "Q9s": [],
                "J9s": [],
                "K9o": [
                    "Kc9d",
                    "Kc9h",
                    "Kc9s",
                    "Kd9c",
                    "Kd9h",
                    "Kd9s",
                    "Kh9c",
                    "Kh9d",
                    "Kh9s",
                    "Ks9c",
                    "Ks9d",
                    "Ks9h"
                ],
                "Q9o": [
                    "Qc9d",
                    "Qc9h",
                    "Qc9s",
                    "Qd9c",
                    "Qd9h",
                    "Qd9s",
                    "Qh9c",
                    "Qh9d",
                    "Qh9s",
                    "Qs9c",
                    "Qs9d",
                    "Qs9h"
                ],
                "J9o": [
                    "Jc9d",
                    "Jc9h",
                    "Jc9s",
                    "Jd9c",
                    "Jd9h",
                    "Jd9s",
                    "Jh9c",
                    "Jh9d",
                    "Jh9s",
                    "Js9c",
                    "Js9d",
                    "Js9h"
                ],
                "TT": [],
                "KQo": [],
                "QJo": [],
                "JTo": [],
                "QTo": [],
                "KTo": [],
                "ATo": [],
                "A9o": [],
                "K3s": [],
                "K2s": [],
                "K5s": [
                    "Kc5c",
                    "Kd5d",
                    "Kh5h",
                    "Ks5s"
                ],
                "Q5s": [],
                "Q4s": [],
                "Q3s": [],
                "Q2s": [],
                "J7s": [],
                "J6s": [],
                "J5s": [],
                "J4s": [],
                "T6s": [],
                "T5s": [],
                "96s": [],
                "64s": [],
                "53s": [],
                "54s": [
                    "5c4c",
                    "5d4d",
                    "5h4h",
                    "5s4s"
                ],
                "65s": [
                    "6c5c",
                    "6d5d",
                    "6h5h",
                    "6s5s"
                ],
                "K4s": [],
                "K6s": [],
                "Q6s": [],
                "Q7s": [],
                "K7s": [],
                "Q8s": [],
                "J8s": [],
                "T8s": [],
                "98s": [],
                "T7s": [],
                "97s": [],
                "87s": [],
                "86s": [],
                "76s": [],
                "75s": [],
                "85s": [],
                "T9s": [
                    "Tc9c",
                    "Td9d",
                    "Th9h",
                    "Ts9s"
                ],
                "T9o": [],
                "98o": [
                    "9c8d",
                    "9c8h",
                    "9c8s",
                    "9d8c",
                    "9d8h",
                    "9d8s",
                    "9h8c",
                    "9h8d",
                    "9h8s",
                    "9s8c",
                    "9s8d",
                    "9s8h"
                ],
                "T8o": [],
                "A8o": [],
                "K8o": [],
                "A7o": [],
                "K7o": [],
                "A6o": [],
                "A4o": [],
                "A5o": [],
                "J2s": [],
                "J3s": [],
                "T3s": [],
                "T4s": [],
                "94s": [],
                "84s": [],
                "83s": [],
                "73s": [],
                "62s": [],
                "52s": [],
                "42s": [],
                "32s": [],
                "43s": [],
                "63s": [],
                "74s": [],
                "95s": [],
                "T2s": [],
                "Q8o": [],
                "J8o": [],
                "A3o": [],
                "A2o": [],
                "K4o": [],
                "K5o": [],
                "K6o": [],
                "Q5o": [],
                "Q6o": [],
                "Q7o": [],
                "J7o": [],
                "T7o": [],
                "97o": [],
                "87o": [],
                "86o": [],
                "76o": [],
                "65o": [],
                "54o": []
            }
        },
        {
            "id": "b74466a6-9fee-4b2e-9e2a-56d367552e63",
            "color": "green",
            "name": "Raise/Fold",
            "selectedCombos": {
                "22": [],
                "33": [],
                "44": [],
                "55": [],
                "66": [],
                "77": [],
                "88": [],
                "99": [],
                "AKs": [],
                "KK": [],
                "AQo": [],
                "AJo": [],
                "KJo": [],
                "QQ": [],
                "JTs": [],
                "JJ": [],
                "AA": [],
                "AKo": [],
                "AQs": [],
                "AJs": [],
                "KQs": [],
                "ATs": [],
                "A9s": [],
                "A8s": [],
                "A7s": [],
                "A4s": [],
                "A5s": [],
                "A6s": [],
                "A3s": [],
                "A2s": [],
                "KJs": [],
                "KTs": [],
                "K8s": [],
                "QJs": [],
                "QTs": [],
                "K9s": [],
                "Q9s": [],
                "J9s": [],
                "K9o": [],
                "Q9o": [],
                "J9o": [],
                "TT": [],
                "KQo": [],
                "QJo": [],
                "JTo": [],
                "QTo": [],
                "KTo": [],
                "ATo": [],
                "A9o": [],
                "K3s": [
                    "Kc3c",
                    "Kd3d",
                    "Kh3h",
                    "Ks3s"
                ],
                "K2s": [
                    "Kc2c",
                    "Kd2d",
                    "Kh2h",
                    "Ks2s"
                ],
                "K5s": [],
                "Q5s": [
                    "Qc5c",
                    "Qd5d",
                    "Qh5h",
                    "Qs5s"
                ],
                "Q4s": [
                    "Qc4c",
                    "Qd4d",
                    "Qh4h",
                    "Qs4s"
                ],
                "Q3s": [
                    "Qc3c",
                    "Qd3d",
                    "Qh3h",
                    "Qs3s"
                ],
                "Q2s": [
                    "Qc2c",
                    "Qd2d",
                    "Qh2h",
                    "Qs2s"
                ],
                "J7s": [
                    "Jc7c",
                    "Jd7d",
                    "Jh7h",
                    "Js7s"
                ],
                "J6s": [
                    "Jc6c",
                    "Jd6d",
                    "Jh6h",
                    "Js6s"
                ],
                "J5s": [
                    "Jc5c",
                    "Jd5d",
                    "Jh5h",
                    "Js5s"
                ],
                "J4s": [
                    "Jc4c",
                    "Jd4d",
                    "Jh4h",
                    "Js4s"
                ],
                "T6s": [
                    "Tc6c",
                    "Td6d",
                    "Th6h",
                    "Ts6s"
                ],
                "T5s": [
                    "Tc5c",
                    "Td5d",
                    "Th5h",
                    "Ts5s"
                ],
                "96s": [
                    "9c6c",
                    "9d6d",
                    "9h6h",
                    "9s6s"
                ],
                "64s": [
                    "6c4c",
                    "6d4d",
                    "6h4h",
                    "6s4s"
                ],
                "53s": [
                    "5c3c",
                    "5d3d",
                    "5h3h",
                    "5s3s"
                ],
                "54s": [],
                "65s": [],
                "K4s": [],
                "K6s": [],
                "Q6s": [],
                "Q7s": [],
                "K7s": [],
                "Q8s": [],
                "J8s": [],
                "T8s": [],
                "98s": [],
                "T7s": [],
                "97s": [],
                "87s": [],
                "86s": [],
                "76s": [],
                "75s": [],
                "85s": [],
                "T9s": [],
                "T9o": [],
                "98o": [],
                "T8o": [
                    "Tc8d",
                    "Tc8h",
                    "Tc8s",
                    "Td8c",
                    "Td8h",
                    "Td8s",
                    "Th8c",
                    "Th8d",
                    "Th8s",
                    "Ts8c",
                    "Ts8d",
                    "Ts8h"
                ],
                "A8o": [
                    "Ac8d",
                    "Ac8h",
                    "Ac8s",
                    "Ad8c",
                    "Ad8h",
                    "Ad8s",
                    "Ah8c",
                    "Ah8d",
                    "Ah8s",
                    "As8c",
                    "As8d",
                    "As8h"
                ],
                "K8o": [
                    "Kc8d",
                    "Kc8h",
                    "Kc8s",
                    "Kd8c",
                    "Kd8h",
                    "Kd8s",
                    "Kh8c",
                    "Kh8d",
                    "Kh8s",
                    "Ks8c",
                    "Ks8d",
                    "Ks8h"
                ],
                "A7o": [
                    "Ac7d",
                    "Ac7h",
                    "Ac7s",
                    "Ad7c",
                    "Ad7h",
                    "Ad7s",
                    "Ah7c",
                    "Ah7d",
                    "Ah7s",
                    "As7c",
                    "As7d",
                    "As7h"
                ],
                "K7o": [
                    "Kc7d",
                    "Kc7h",
                    "Kc7s",
                    "Kd7c",
                    "Kd7h",
                    "Kd7s",
                    "Kh7c",
                    "Kh7d",
                    "Kh7s",
                    "Ks7c",
                    "Ks7d",
                    "Ks7h"
                ],
                "A6o": [
                    "Ac6d",
                    "Ac6h",
                    "Ac6s",
                    "Ad6c",
                    "Ad6h",
                    "Ad6s",
                    "Ah6c",
                    "Ah6d",
                    "Ah6s",
                    "As6c",
                    "As6d",
                    "As6h"
                ],
                "A4o": [
                    "Ac4d",
                    "Ac4h",
                    "Ac4s",
                    "Ad4c",
                    "Ad4h",
                    "Ad4s",
                    "Ah4c",
                    "Ah4d",
                    "Ah4s",
                    "As4c",
                    "As4d",
                    "As4h"
                ],
                "A5o": [],
                "J2s": [],
                "J3s": [],
                "T3s": [],
                "T4s": [],
                "94s": [],
                "84s": [],
                "83s": [],
                "73s": [],
                "62s": [],
                "52s": [],
                "42s": [],
                "32s": [],
                "43s": [],
                "63s": [],
                "74s": [],
                "95s": [],
                "T2s": [],
                "Q8o": [],
                "J8o": [],
                "A3o": [],
                "A2o": [],
                "K4o": [],
                "K5o": [],
                "K6o": [],
                "Q5o": [],
                "Q6o": [],
                "Q7o": [],
                "J7o": [],
                "T7o": [],
                "97o": [],
                "87o": [],
                "86o": [],
                "76o": [],
                "65o": [],
                "54o": []
            }
        },
        {
            "id": "4daee86b-5b5e-4d04-9090-07a46dbf66eb",
            "color": "cyan",
            "name": "Limp/Raise",
            "selectedCombos": {
                "22": [],
                "33": [],
                "44": [],
                "55": [],
                "66": [],
                "77": [],
                "88": [
                    "8c8d",
                    "8c8h",
                    "8c8s",
                    "8d8h",
                    "8d8s",
                    "8h8s"
                ],
                "99": [
                    "9c9d",
                    "9c9h",
                    "9c9s",
                    "9d9h",
                    "9d9s",
                    "9h9s"
                ],
                "AKs": [],
                "KK": [],
                "AQo": [],
                "AJo": [],
                "KJo": [],
                "QQ": [],
                "JTs": [],
                "JJ": [],
                "AA": [
                    "AcAd",
                    "AcAh",
                    "AcAs",
                    "AdAh",
                    "AdAs",
                    "AhAs"
                ],
                "AKo": [
                    "AcKd",
                    "AcKh",
                    "AcKs",
                    "AdKc",
                    "AdKh",
                    "AdKs",
                    "AhKc",
                    "AhKd",
                    "AhKs",
                    "AsKc",
                    "AsKd",
                    "AsKh"
                ],
                "AQs": [
                    "AcQc",
                    "AdQd",
                    "AhQh",
                    "AsQs"
                ],
                "AJs": [
                    "AcJc",
                    "AdJd",
                    "AhJh",
                    "AsJs"
                ],
                "KQs": [
                    "KcQc",
                    "KdQd",
                    "KhQh",
                    "KsQs"
                ],
                "ATs": [],
                "A9s": [],
                "A8s": [],
                "A7s": [],
                "A4s": [],
                "A5s": [],
                "A6s": [],
                "A3s": [],
                "A2s": [],
                "KJs": [],
                "KTs": [],
                "K8s": [],
                "QJs": [],
                "QTs": [],
                "K9s": [
                    "Kc9c",
                    "Kd9d",
                    "Kh9h",
                    "Ks9s"
                ],
                "Q9s": [
                    "Qc9c",
                    "Qd9d",
                    "Qh9h",
                    "Qs9s"
                ],
                "J9s": [
                    "Jc9c",
                    "Jd9d",
                    "Jh9h",
                    "Js9s"
                ],
                "K9o": [],
                "Q9o": [],
                "J9o": [],
                "TT": [
                    "TcTd",
                    "TcTh",
                    "TcTs",
                    "TdTh",
                    "TdTs",
                    "ThTs"
                ],
                "KQo": [],
                "QJo": [],
                "JTo": [],
                "QTo": [],
                "KTo": [],
                "ATo": [],
                "A9o": [],
                "K3s": [],
                "K2s": [],
                "K5s": [],
                "Q5s": [],
                "Q4s": [],
                "Q3s": [],
                "Q2s": [],
                "J7s": [],
                "J6s": [],
                "J5s": [],
                "J4s": [],
                "T6s": [],
                "T5s": [],
                "96s": [],
                "64s": [],
                "53s": [],
                "54s": [],
                "65s": [],
                "K4s": [],
                "K6s": [],
                "Q6s": [],
                "Q7s": [],
                "K7s": [],
                "Q8s": [],
                "J8s": [],
                "T8s": [],
                "98s": [
                    "9c8c",
                    "9d8d",
                    "9h8h",
                    "9s8s"
                ],
                "T7s": [],
                "97s": [],
                "87s": [
                    "8c7c",
                    "8d7d",
                    "8h7h",
                    "8s7s"
                ],
                "86s": [],
                "76s": [],
                "75s": [],
                "85s": [],
                "T9s": [],
                "T9o": [],
                "98o": [],
                "T8o": [],
                "A8o": [],
                "K8o": [],
                "A7o": [],
                "K7o": [],
                "A6o": [],
                "A4o": [],
                "A5o": [],
                "J2s": [],
                "J3s": [],
                "T3s": [],
                "T4s": [],
                "94s": [],
                "84s": [],
                "83s": [],
                "73s": [],
                "62s": [],
                "52s": [],
                "42s": [],
                "32s": [],
                "43s": [],
                "63s": [],
                "74s": [],
                "95s": [],
                "T2s": [],
                "Q8o": [],
                "J8o": [],
                "A3o": [],
                "A2o": [],
                "K4o": [],
                "K5o": [],
                "K6o": [],
                "Q5o": [],
                "Q6o": [],
                "Q7o": [],
                "J7o": [],
                "T7o": [],
                "97o": [],
                "87o": [],
                "86o": [],
                "76o": [],
                "65o": [],
                "54o": []
            }
        },
        {
            "id": "b8faaedb-7c80-412a-810e-fc0601e41e75",
            "color": "orange",
            "name": "Limp/Call",
            "selectedCombos": {
                "22": [],
                "33": [],
                "44": [
                    "4c4d",
                    "4c4h",
                    "4c4s",
                    "4d4h",
                    "4d4s",
                    "4h4s"
                ],
                "55": [
                    "5c5d",
                    "5c5h",
                    "5c5s",
                    "5d5h",
                    "5d5s",
                    "5h5s"
                ],
                "66": [
                    "6c6d",
                    "6c6h",
                    "6c6s",
                    "6d6h",
                    "6d6s",
                    "6h6s"
                ],
                "77": [
                    "7c7d",
                    "7c7h",
                    "7c7s",
                    "7d7h",
                    "7d7s",
                    "7h7s"
                ],
                "88": [],
                "99": [],
                "AKs": [],
                "KK": [],
                "AQo": [],
                "AJo": [],
                "KJo": [],
                "QQ": [],
                "JTs": [],
                "JJ": [],
                "AA": [],
                "AKo": [],
                "AQs": [],
                "AJs": [],
                "KQs": [],
                "ATs": [],
                "A9s": [],
                "A8s": [],
                "A7s": [],
                "A4s": [
                    "Ac4c",
                    "Ad4d",
                    "Ah4h",
                    "As4s"
                ],
                "A5s": [],
                "A6s": [
                    "Ac6c",
                    "Ad6d",
                    "Ah6h",
                    "As6s"
                ],
                "A3s": [
                    "Ac3c",
                    "Ad3d",
                    "Ah3h",
                    "As3s"
                ],
                "A2s": [
                    "Ac2c",
                    "Ad2d",
                    "Ah2h",
                    "As2s"
                ],
                "KJs": [],
                "KTs": [],
                "K8s": [],
                "QJs": [],
                "QTs": [],
                "K9s": [],
                "Q9s": [],
                "J9s": [],
                "K9o": [],
                "Q9o": [],
                "J9o": [],
                "TT": [],
                "KQo": [
                    "KcQd",
                    "KcQh",
                    "KcQs",
                    "KdQc",
                    "KdQh",
                    "KdQs",
                    "KhQc",
                    "KhQd",
                    "KhQs",
                    "KsQc",
                    "KsQd",
                    "KsQh"
                ],
                "QJo": [
                    "QcJd",
                    "QcJh",
                    "QcJs",
                    "QdJc",
                    "QdJh",
                    "QdJs",
                    "QhJc",
                    "QhJd",
                    "QhJs",
                    "QsJc",
                    "QsJd",
                    "QsJh"
                ],
                "JTo": [
                    "JcTd",
                    "JcTh",
                    "JcTs",
                    "JdTc",
                    "JdTh",
                    "JdTs",
                    "JhTc",
                    "JhTd",
                    "JhTs",
                    "JsTc",
                    "JsTd",
                    "JsTh"
                ],
                "QTo": [
                    "QcTd",
                    "QcTh",
                    "QcTs",
                    "QdTc",
                    "QdTh",
                    "QdTs",
                    "QhTc",
                    "QhTd",
                    "QhTs",
                    "QsTc",
                    "QsTd",
                    "QsTh"
                ],
                "KTo": [
                    "KcTd",
                    "KcTh",
                    "KcTs",
                    "KdTc",
                    "KdTh",
                    "KdTs",
                    "KhTc",
                    "KhTd",
                    "KhTs",
                    "KsTc",
                    "KsTd",
                    "KsTh"
                ],
                "ATo": [
                    "AcTd",
                    "AcTh",
                    "AcTs",
                    "AdTc",
                    "AdTh",
                    "AdTs",
                    "AhTc",
                    "AhTd",
                    "AhTs",
                    "AsTc",
                    "AsTd",
                    "AsTh"
                ],
                "A9o": [
                    "Ac9d",
                    "Ac9h",
                    "Ac9s",
                    "Ad9c",
                    "Ad9h",
                    "Ad9s",
                    "Ah9c",
                    "Ah9d",
                    "Ah9s",
                    "As9c",
                    "As9d",
                    "As9h"
                ],
                "K3s": [],
                "K2s": [],
                "K5s": [],
                "Q5s": [],
                "Q4s": [],
                "Q3s": [],
                "Q2s": [],
                "J7s": [],
                "J6s": [],
                "J5s": [],
                "J4s": [],
                "T6s": [],
                "T5s": [],
                "96s": [],
                "64s": [],
                "53s": [],
                "54s": [],
                "65s": [],
                "K4s": [
                    "Kc4c",
                    "Kd4d",
                    "Kh4h",
                    "Ks4s"
                ],
                "K6s": [
                    "Kc6c",
                    "Kd6d",
                    "Kh6h",
                    "Ks6s"
                ],
                "Q6s": [
                    "Qc6c",
                    "Qd6d",
                    "Qh6h",
                    "Qs6s"
                ],
                "Q7s": [
                    "Qc7c",
                    "Qd7d",
                    "Qh7h",
                    "Qs7s"
                ],
                "K7s": [
                    "Kc7c",
                    "Kd7d",
                    "Kh7h",
                    "Ks7s"
                ],
                "Q8s": [
                    "Qc8c",
                    "Qd8d",
                    "Qh8h",
                    "Qs8s"
                ],
                "J8s": [
                    "Jc8c",
                    "Jd8d",
                    "Jh8h",
                    "Js8s"
                ],
                "T8s": [
                    "Tc8c",
                    "Td8d",
                    "Th8h",
                    "Ts8s"
                ],
                "98s": [],
                "T7s": [
                    "Tc7c",
                    "Td7d",
                    "Th7h",
                    "Ts7s"
                ],
                "97s": [
                    "9c7c",
                    "9d7d",
                    "9h7h",
                    "9s7s"
                ],
                "87s": [],
                "86s": [
                    "8c6c",
                    "8d6d",
                    "8h6h",
                    "8s6s"
                ],
                "76s": [
                    "7c6c",
                    "7d6d",
                    "7h6h",
                    "7s6s"
                ],
                "75s": [
                    "7c5c",
                    "7d5d",
                    "7h5h",
                    "7s5s"
                ],
                "85s": [
                    "8c5c",
                    "8d5d",
                    "8h5h",
                    "8s5s"
                ],
                "T9s": [],
                "T9o": [
                    "Tc9d",
                    "Tc9h",
                    "Tc9s",
                    "Td9c",
                    "Td9h",
                    "Td9s",
                    "Th9c",
                    "Th9d",
                    "Th9s",
                    "Ts9c",
                    "Ts9d",
                    "Ts9h"
                ],
                "98o": [],
                "T8o": [],
                "A8o": [],
                "K8o": [],
                "A7o": [],
                "K7o": [],
                "A6o": [],
                "A4o": [],
                "A5o": [
                    "Ac5d",
                    "Ac5h",
                    "Ac5s",
                    "Ad5c",
                    "Ad5h",
                    "Ad5s",
                    "Ah5c",
                    "Ah5d",
                    "Ah5s",
                    "As5c",
                    "As5d",
                    "As5h"
                ],
                "J2s": [],
                "J3s": [],
                "T3s": [],
                "T4s": [],
                "94s": [],
                "84s": [],
                "83s": [],
                "73s": [],
                "62s": [],
                "52s": [],
                "42s": [],
                "32s": [],
                "43s": [],
                "63s": [],
                "74s": [],
                "95s": [],
                "T2s": [],
                "Q8o": [],
                "J8o": [],
                "A3o": [],
                "A2o": [],
                "K4o": [],
                "K5o": [],
                "K6o": [],
                "Q5o": [],
                "Q6o": [],
                "Q7o": [],
                "J7o": [],
                "T7o": [],
                "97o": [],
                "87o": [],
                "86o": [],
                "76o": [],
                "65o": [],
                "54o": []
            }
        },
        {
            "id": "4e0f8437-63d8-4ed5-b083-3ff9fa11d83d",
            "color": "purple",
            "name": "Limp/Fold",
            "selectedCombos": {
                "22": [],
                "33": [],
                "44": [],
                "55": [],
                "66": [],
                "77": [],
                "88": [],
                "99": [],
                "AKs": [],
                "KK": [],
                "AQo": [],
                "AJo": [],
                "KJo": [],
                "QQ": [],
                "JTs": [],
                "JJ": [],
                "AA": [],
                "AKo": [],
                "AQs": [],
                "AJs": [],
                "KQs": [],
                "ATs": [],
                "A9s": [],
                "A8s": [],
                "A7s": [],
                "A4s": [],
                "A5s": [],
                "A6s": [],
                "A3s": [],
                "A2s": [],
                "KJs": [],
                "KTs": [],
                "K8s": [],
                "QJs": [],
                "QTs": [],
                "K9s": [],
                "Q9s": [],
                "J9s": [],
                "K9o": [],
                "Q9o": [],
                "J9o": [],
                "TT": [],
                "KQo": [],
                "QJo": [],
                "JTo": [],
                "QTo": [],
                "KTo": [],
                "ATo": [],
                "A9o": [],
                "K3s": [],
                "K2s": [],
                "K5s": [],
                "Q5s": [],
                "Q4s": [],
                "Q3s": [],
                "Q2s": [],
                "J7s": [],
                "J6s": [],
                "J5s": [],
                "J4s": [],
                "T6s": [],
                "T5s": [],
                "96s": [],
                "64s": [],
                "53s": [],
                "54s": [],
                "65s": [],
                "K4s": [],
                "K6s": [],
                "Q6s": [],
                "Q7s": [],
                "K7s": [],
                "Q8s": [],
                "J8s": [],
                "T8s": [],
                "98s": [],
                "T7s": [],
                "97s": [],
                "87s": [],
                "86s": [],
                "76s": [],
                "75s": [],
                "85s": [],
                "T9s": [],
                "T9o": [],
                "98o": [],
                "T8o": [],
                "A8o": [],
                "K8o": [],
                "A7o": [],
                "K7o": [],
                "A6o": [],
                "A4o": [],
                "A5o": [],
                "J2s": [
                    "Jc2c",
                    "Jd2d",
                    "Jh2h",
                    "Js2s"
                ],
                "J3s": [
                    "Jc3c",
                    "Jd3d",
                    "Jh3h",
                    "Js3s"
                ],
                "T3s": [
                    "Tc3c",
                    "Td3d",
                    "Th3h",
                    "Ts3s"
                ],
                "T4s": [
                    "Tc4c",
                    "Td4d",
                    "Th4h",
                    "Ts4s"
                ],
                "94s": [
                    "9c4c",
                    "9d4d",
                    "9h4h",
                    "9s4s"
                ],
                "84s": [
                    "8c4c",
                    "8d4d",
                    "8h4h",
                    "8s4s"
                ],
                "83s": [],
                "73s": [],
                "62s": [],
                "52s": [],
                "42s": [],
                "32s": [],
                "43s": [
                    "4c3c",
                    "4d3d",
                    "4h3h",
                    "4s3s"
                ],
                "63s": [
                    "6c3c",
                    "6d3d",
                    "6h3h",
                    "6s3s"
                ],
                "74s": [
                    "7c4c",
                    "7d4d",
                    "7h4h",
                    "7s4s"
                ],
                "95s": [
                    "9c5c",
                    "9d5d",
                    "9h5h",
                    "9s5s"
                ],
                "T2s": [],
                "Q8o": [
                    "Qc8d",
                    "Qc8h",
                    "Qc8s",
                    "Qd8c",
                    "Qd8h",
                    "Qd8s",
                    "Qh8c",
                    "Qh8d",
                    "Qh8s",
                    "Qs8c",
                    "Qs8d",
                    "Qs8h"
                ],
                "J8o": [
                    "Jc8d",
                    "Jc8h",
                    "Jc8s",
                    "Jd8c",
                    "Jd8h",
                    "Jd8s",
                    "Jh8c",
                    "Jh8d",
                    "Jh8s",
                    "Js8c",
                    "Js8d",
                    "Js8h"
                ],
                "A3o": [
                    "Ac3d",
                    "Ac3h",
                    "Ac3s",
                    "Ad3c",
                    "Ad3h",
                    "Ad3s",
                    "Ah3c",
                    "Ah3d",
                    "Ah3s",
                    "As3c",
                    "As3d",
                    "As3h"
                ],
                "A2o": [
                    "Ac2d",
                    "Ac2h",
                    "Ac2s",
                    "Ad2c",
                    "Ad2h",
                    "Ad2s",
                    "Ah2c",
                    "Ah2d",
                    "Ah2s",
                    "As2c",
                    "As2d",
                    "As2h"
                ],
                "K4o": [
                    "Kc4d",
                    "Kc4h",
                    "Kc4s",
                    "Kd4c",
                    "Kd4h",
                    "Kd4s",
                    "Kh4c",
                    "Kh4d",
                    "Kh4s",
                    "Ks4c",
                    "Ks4d",
                    "Ks4h"
                ],
                "K5o": [
                    "Kc5d",
                    "Kc5h",
                    "Kc5s",
                    "Kd5c",
                    "Kd5h",
                    "Kd5s",
                    "Kh5c",
                    "Kh5d",
                    "Kh5s",
                    "Ks5c",
                    "Ks5d",
                    "Ks5h"
                ],
                "K6o": [
                    "Kc6d",
                    "Kc6h",
                    "Kc6s",
                    "Kd6c",
                    "Kd6h",
                    "Kd6s",
                    "Kh6c",
                    "Kh6d",
                    "Kh6s",
                    "Ks6c",
                    "Ks6d",
                    "Ks6h"
                ],
                "Q5o": [
                    "Qc5d",
                    "Qc5h",
                    "Qc5s",
                    "Qd5c",
                    "Qd5h",
                    "Qd5s",
                    "Qh5c",
                    "Qh5d",
                    "Qh5s",
                    "Qs5c",
                    "Qs5d",
                    "Qs5h"
                ],
                "Q6o": [
                    "Qc6d",
                    "Qc6h",
                    "Qc6s",
                    "Qd6c",
                    "Qd6h",
                    "Qd6s",
                    "Qh6c",
                    "Qh6d",
                    "Qh6s",
                    "Qs6c",
                    "Qs6d",
                    "Qs6h"
                ],
                "Q7o": [
                    "Qc7d",
                    "Qc7h",
                    "Qc7s",
                    "Qd7c",
                    "Qd7h",
                    "Qd7s",
                    "Qh7c",
                    "Qh7d",
                    "Qh7s",
                    "Qs7c",
                    "Qs7d",
                    "Qs7h"
                ],
                "J7o": [
                    "Jc7d",
                    "Jc7h",
                    "Jc7s",
                    "Jd7c",
                    "Jd7h",
                    "Jd7s",
                    "Jh7c",
                    "Jh7d",
                    "Jh7s",
                    "Js7c",
                    "Js7d",
                    "Js7h"
                ],
                "T7o": [
                    "Tc7d",
                    "Tc7h",
                    "Tc7s",
                    "Td7c",
                    "Td7h",
                    "Td7s",
                    "Th7c",
                    "Th7d",
                    "Th7s",
                    "Ts7c",
                    "Ts7d",
                    "Ts7h"
                ],
                "97o": [
                    "9c7d",
                    "9c7h",
                    "9c7s",
                    "9d7c",
                    "9d7h",
                    "9d7s",
                    "9h7c",
                    "9h7d",
                    "9h7s",
                    "9s7c",
                    "9s7d",
                    "9s7h"
                ],
                "87o": [
                    "8c7d",
                    "8c7h",
                    "8c7s",
                    "8d7c",
                    "8d7h",
                    "8d7s",
                    "8h7c",
                    "8h7d",
                    "8h7s",
                    "8s7c",
                    "8s7d",
                    "8s7h"
                ],
                "86o": [
                    "8c6d",
                    "8c6h",
                    "8c6s",
                    "8d6c",
                    "8d6h",
                    "8d6s",
                    "8h6c",
                    "8h6d",
                    "8h6s",
                    "8s6c",
                    "8s6d",
                    "8s6h"
                ],
                "76o": [
                    "7c6d",
                    "7c6h",
                    "7c6s",
                    "7d6c",
                    "7d6h",
                    "7d6s",
                    "7h6c",
                    "7h6d",
                    "7h6s",
                    "7s6c",
                    "7s6d",
                    "7s6h"
                ],
                "65o": [],
                "54o": []
            }
        }
    ],
    type: types.range
}