export const types = {
  ADD_RANGE: '@my-poker-review/range-builder/ADD_RANGE',
  CLEAR_ALL: '@my-poker-review/range-builder/CLEAR_ALL',
  CLEAR_ALL_SELECTED_COMBOS: '@my-poker-review/range-builder/CLEAR_ALL_SELECTED_COMBOS',
  CLEAR_BOARD: '@my-poker-review/range-builder/CLEAR_BOARD',
  CLEAR_HAND: '@my-poker-review/range-builder/CLEAR_HAND',
  CLEAR_SELECTED_COMBOS_FROM_RANGE: '@my-poker-review/range-builder/CLEAR_SELECTED_COMBOS_FROM_RANGE',
  CLEAR_SELECTED_COMBO_GROUP_IDS: '@my-poker-review/range-builder/CLEAR_SELECTED_COMBO_GROUP_IDS',
  DELETE_RANGE: '@my-poker-review/range-builder/DELETE_RANGE',
  EXPORT_RANGES_FAILURE: '@my-poker-review/range-builder/EXPORT_RANGES_FAILURE',
  EXPORT_RANGES_SUCCESS: '@my-poker-review/range-builder/EXPORT_RANGES_SUCCESS',
  IMPORT_RANGES_INIT: '@my-poker-review/range-builder/IMPORT_RANGES_INIT',
  IMPORT_RANGES_FAILURE: '@my-poker-review/range-builder/IMPORT_RANGES_FAILURE',
  IMPORT_RANGES_SUCCESS: '@my-poker-review/range-builder/IMPORT_RANGES_SUCCESS',
  SELECT_BOARD_CARDS: '@my-poker-review/range-builder/SELECT_BOARD_CARDS',
  SELECT_COMBOS: '@my-poker-review/range-builder/SELECT_COMBOS',
  SELECT_HAND_CARDS: '@my-poker-review/range-builder/SELECT_HAND_CARDS',
  SELECT_RANGE: '@my-poker-review/range-builder/SELECT_RANGE',
  SET_ADD_RANGE_MENU_OPEN: '@my-poker-review/range-builder/SET_ADD_RANGE_MENU_OPEN',
  SET_BOARD: '@my-poker-review/range-builder/SET_BOARD',
  SET_EDITING: '@my-poker-review/range-builder/SET_EDITING',
  SET_EXPORT_DIALOG_OPEN: '@my-poker-review/range-builder/SET_EXPORT_DIALOG_OPEN',
  SET_EXPORT_FILE_NAME: '@my-poker-review/range-builder/SET_EXPORT_FILE_NAME',
  SET_HAND: '@my-poker-review/range-builder/SET_HAND',
  SET_IMPORT_DIALOG_OPEN: '@my-poker-review/range-builder/SET_IMPORT_DIALOG_OPEN',
  SET_IMPORT_FILE: '@my-poker-review/range-builder/SET_IMPORT_FILE',
  SET_RANGE_NAME: '@my-poker-review/range-builder/SET_RANGE_NAME',
  SET_SELECTING: '@my-poker-review/range-builder/SET_SELECTING',
  SET_SELECTING_SUITS: '@my-poker-review/range-builder/SET_SELECTING_SUITS'
}

export const comboRows = [
  ['AA','AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s'],
  ['AKo','KK','KQs','KJs','KTs','K9s','K8s','K7s','K6s','K5s','K4s','K3s','K2s'],
  ['AQo','KQo','QQ','QJs','QTs','Q9s','Q8s','Q7s','Q6s','Q5s','Q4s','Q3s','Q2s'],
  ['AJo','KJo','QJo','JJ','JTs','J9s','J8s','J7s','J6s','J5s','J4s','J3s','J2s'],
  ['ATo','KTo','QTo','JTo','TT','T9s','T8s','T7s','T6s','T5s','T4s','T3s','T2s'],
  ['A9o','K9o','Q9o','J9o','T9o','99','98s','97s','96s','95s','94s','93s','92s'],
  ['A8o','K8o','Q8o','J8o','T8o','98o','88','87s','86s','85s','84s','83s','82s'],
  ['A7o','K7o','Q7o','J7o','T7o','97o','87o','77','76s','75s','74s','73s','72s'],
  ['A6o','K6o','Q6o','J6o','T6o','96o','86o','76o','66','65s','64s','63s','62s'],
  ['A5o','K5o','Q5o','J5o','T5o','95o','85o','75o','65o','55','54s','53s','52s'],
  ['A4o','K4o','Q4o','J4o','T4o','94o','84o','74o','64o','54o','44','43s','42s'],
  ['A3o','K3o','Q3o','J3o','T3o','93o','83o','73o','63o','53o','43o','33','32s'],
  ['A2o','K2o','Q2o','J2o','T2o','92o','82o','72o','62o','52o','42o','32o','22']
]
